parameters:
  pool:
  azureSubscription:
  location: 'West Europe'
  environmentName:
  clusterConnection:
  serviceConnectionName:
jobs:
- deployment: DeployProviderAdjustments
  pool:
    name: ${{ parameters.pool }}
    demands:
    - ReleaseEnvironment -equals ${{ parameters.environmentName }}
  environment: ${{ parameters.environmentName }}
  variables:
    PAAppFilter: 'SFA.DAS.Payments.ProviderAdjustments'
  
  strategy:
    runOnce:
      deploy:
        steps:
        - task: ServiceFabricPowerShell@1
          displayName: 'Remove DAS Payments - ProviderAdjustments'
          inputs:
            clusterConnection: ${{ parameters.clusterConnection }}
            ScriptPath: 'pipeline-templates/RemoveServiceFabricApps.ps1'
            ScriptArguments: '-applicationFilter $(PAAppFilter)'
            continueOnError: true

        - task: ServiceFabricDeploy@1
          displayName: 'Deploy Service Fabric Application - DAS_Payment - ProviderAdjustments'
          inputs:
            applicationPackagePath: '$(system.defaultworkingdirectory)/**/provideradjustments-drop/applicationpackage'
            serviceConnectionName: ${{ parameters.serviceConnectionName }}
            publishProfilePath: '$(system.defaultworkingdirectory)/**/provideradjustments-drop/PublishProfiles/Cloud.xml'
            applicationParameterPath: '$(System.DefaultWorkingDirectory)/**/provideradjustments-drop/ApplicationParameters/Cloud.xml'
            compressPackage: true
            skipUpgradeSameTypeAndVersion: true
            overridePublishProfileSettings: true
            upgradeMode: UnmonitoredAuto
            UpgradeReplicaSetCheckTimeoutSec: 600000
            TimeoutSec: 600000
            continueOnError: true
            timeoutInMinutes: 65
