parameters:
  pool:
  azureSubscription:
  location: 'West Europe'
  environmentName:
  clusterConnection:
  serviceConnectionName:
jobs:
- deployment: DeployProviderAdjustments
  pool:
    name: ${{ parameters.pool }}
    demands:
    - ReleaseEnvironment -equals ${{ parameters.environmentName }}
    workspace:
      clean: all
  environment: ${{ parameters.environmentName }}
  variables:
    PAAppFilter: 'SFA.DAS.Payments.ProviderAdjustments'
  
  strategy:
    runOnce:
      deploy:
        steps:
        - task: ServiceFabricPowerShell@1
          displayName: 'Remove DAS Payments - ProviderAdjustments'
          inputs:
            ConnectionType: 'ClusterConnection'
            serviceConnectionName: ${{ parameters.serviceConnectionName }}
            clusterConnectionName: ${{ parameters.clusterConnection }}
            ScriptType: 'InlineScript'
            InlineScript: |
              Remove-ServiceFabricApplication -ApplicationName fabric:/SFA.DAS.Payments.ProviderAdjustments.ServiceFabric -Force
            #filePath: '$(Pipeline.Workspace)/publish/RemoveServiceFabricApps.ps1'
            #ScriptArguments: '-applicationFilter $(PAAppFilter)'
            #continueOnError: true

        - task: TotalALM.totalalm-tokenization.tokenization-build-task.Tokenization@2
          displayName: 'Tokenization: Transform ApplicationParameters file Cloud.xml'
          inputs:
            SourcePath: '$(Pipeline.Workspace)\**'
            TargetFileNames: Cloud.xml
            RequireVariable: true

        - task: ServiceFabricDeploy@1
          displayName: 'Deploy Service Fabric Application - DAS_Payment - ProviderAdjustments'
          inputs:
            applicationPackagePath: '$(build.artifactstagingdirectory)/provideradjustmentsV2/ApplicationPackage'
            serviceConnectionName: ${{ parameters.serviceConnectionName }}
            publishProfilePath: '$(build.artifactstagingdirectory)/provideradjustmentsV2/provideradjustments/PublishProfiles/Cloud.xml'
            applicationParameterPath: '$(build.artifactstagingdirectory)/provideradjustmentsV2/provideradjustments/ApplicationParameters/Cloud.xml'
            applicationName: 'SFA.DAS.Payments.ProviderAdjustments'
            compressPackage: true
            skipUpgradeSameTypeAndVersion: true
            overridePublishProfileSettings: true
            upgradeMode: UnmonitoredAuto
            UpgradeReplicaSetCheckTimeoutSec: 600000
            TimeoutSec: 600000
            continueOnError: true
            timeoutInMinutes: 65
